fix: navbar light-mode ui bug fix
UniKonf/Vibey pull request #124
Opened 2023-05-15 15:20 UTC by SirSimon162

Closes: #123 

Changes made

Changed the color of Hamburger icon in Navbar in light mode and changed the background color of 'Get Started' button in light mode.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

I have verified the changes locally and i have attached screenshots of it.

##Before
![issue1](https://github.com/UniKonf/vibey/assets/103681122/c1563f1e-5d29-4f20-9f76-3914fd23468a)
![issue 2](https://github.com/UniKonf/vibey/assets/103681122/e5e15f9f-0258-47c2-a6db-dcc2a6d6e2f9)

##After
![resolve1](https://github.com/UniKonf/vibey/assets/103681122/de588b9a-81c2-4863-bc9e-0c02f80631c8)
![resolve2](https://github.com/UniKonf/vibey/assets/103681122/2e0e943f-b612-48e1-aa56-0c65b138dffd)

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

2023-05-15 15:23 UTC, SirSimon162 commented
Hey @Deepu178 can you please review this pr

2023-05-15 16:28 UTC, Deepu178 requested changes
use yarn package manager for installation

2023-05-15 17:48 UTC, SirSimon162 commented
@Deepu178 fixed that mistake

2023-05-16 14:51 UTC, Deepu178 approved these changes

2023-05-16 14:51 UTC, merged