Added the scroll to top button
UniKonf/Vibey pull request #198
Opened 2023-05-25 13:49 UTC by abhinav-m22

## Related Issue

- Information about the related issue

* Closes:- # 168

### Describe the changes you've made

Added the scroll to top nav button at the bottom right corner of the web page.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have setup the website on my local environment and then run it and tested the changes.

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| 
<img width="955" alt="image" src="https://github.com/UniKonf/vibey/assets/113239388/622034bc-dc57-492f-ad7d-092920222ae4">
 | <img width="960" alt="image" src="https://github.com/UniKonf/vibey/assets/113239388/124796b3-7e3f-413a-8c70-4cdaaac33045"> |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

2023-05-26 18:29 UTC, Deepu178 requested changes
You are using npm for package management but we are using yarn package manger.
You are writing pure css while we are using tailwindCSS.
I would suggest you to make those changes and commit it.

2023-05-29 07:24 UTC, arunavabasu-03 commented
I would like to work on this!

2023-05-29 07:30 UTC, abhinav-m22 commented
Hey @arunavabasu-03 
I've already made the changes.. There are just some conflicts so I'm resolving it.... Please find some other issue

2023-05-29 07:51 UTC, abhinav-m22 commented
Hey @Deepu178 
I've made the required changes.. Please check

2023-05-29 07:53 UTC, abhinav-m22 commented
Hey @Deepu178 
I have made the required changes... Please check

2023-05-29 09:22 UTC, parthpathakpp1 commented
> Hey @Deepu178 I have made the required changes... Please check

@abhinav-m22 I need some help . Can you share your Discord ID.

2023-05-30 15:41 UTC, Deepu178 commented
@abhinav-m22 You are still using npm packages to install the dependecies. I would suggest few steps to resolve this error.
1. Delete package-lock.json file
2. Run yarn command
3. Commit the changes
Just follow these steps and it will be ready to merge.

2023-05-30 17:24 UTC, abhinav-m22 commented
Hey @arunavabasu-03 Thanks for helping me out.
I've followed the steps you told.
But there were many conflicts from my side in the repo... I've resolved them.. But if there are any issues, please let me know.
I'll create a new PR if any problem exists.
Thank you!

2023-06-01 13:52 UTC, abhinav-m22 commented
@Deepu178 Any updates?

2023-06-03 06:50 UTC, Deepu178 requested changes
@abhinav-m22 you are still using npm package manager for installation and I would suggest you to install dependencies usin yarn.

2023-06-03 06:50 UTC, Deepu178 commented on src/styles/globals.css
> +
@abhinav-m22  we are using Yarn package manager for installing dependencies and not npm package manager for installation.
Please remove package-lock.json file and install the dependencies using yarn.
Commit those changes.

2023-06-07 10:55 UTC, Deepu178 commented
@abhinav-m22  Are you still working on this issue?

2023-06-07 14:51 UTC, rushabhpanbude commented
> @abhinav-m22 Are you still working on this issue?

You can pass this task to me

2023-06-10 03:46 UTC, closed without merging

2023-06-10 03:47 UTC, Deepu178 commented
This feature has been added through other pr so looking forward for more contribution from your side.