feat: password visibility button added for signup
UniKonf/Vibey pull request #241
Opened 2023-06-02 17:59 UTC by SINJINI-G

## Related Issue
- added password visibility button

Closes: #170 

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)
![poc](https://github.com/UniKonf/vibey/assets/98143022/f178a85d-a0e7-401c-8a45-83cd2134a8fb)

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

2023-06-03 06:18 UTC, Deepu178 requested changes
@SINJINI-G  we are using Yarn package manager for installing dependencies and not npm package manager for installation. 
Please remove package-lock.json file and install the dependencies using yarn.
Commit those changes.

2023-06-03 14:56 UTC, SINJINI-G commented
> @SINJINI-G we are using Yarn package manager for installing dependencies and not npm package manager for installation. Please remove package-lock.json file and install the dependencies using yarn. Commit those changes.

changes have been done. Kindly checked

2023-06-15 16:59 UTC, Deepu178 commented
@SINJINI-G This branch has conflicts that must be resolved so please work on it and I can review your pr as early as possible.

2023-06-16 03:59 UTC, SINJINI-G commented
> @SINJINI-G This branch has conflicts that must be resolved so please work on it and I can review your pr as early as possible.

Conflicts resolved. Please check.

2023-06-16 04:04 UTC, Deepu178 reviewed
![overflow](https://github.com/UniKonf/vibey/assets/68677868/bcf0b435-23c7-4945-9f5c-3f3599e03d29)

@SINJINI-G  you can see here that icons are coming out of input field. Please fix it so this pr is ready for merge.

2023-06-18 09:39 UTC, Deepu178 commented
@SINJINI-G Any update?

2023-07-04 04:23 UTC, Deepu178 commented
Any update @SINJINI-G  on this pr?

2023-07-17 10:04 UTC, closed without merging