feat: add server
UniKonf/Vibey pull request #329
Opened 2023-06-24 16:39 UTC by suzy-g38

## Related Issue

- Information about the related issue

Closes: #262

What sort of change have you made:

Added server

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/UniKonf/vibey/blob/main/CODE_OF_CONDUCT.md)

2023-06-25 14:54 UTC, Deepu178 approved these changes

2023-06-25 15:51 UTC, Deepu178 requested changes
@suzy-g38 Please review and fix the security vulnerabilities.

2023-06-27 11:16 UTC, Deepu178 commented
Thanks @suzy-g38  for making the biggest contribution to the Vibey.  You have done a really great job and implemented it perfectly. Let's merge the pr!

2023-06-27 11:16 UTC, merged

2023-06-27 12:14 UTC, suzy-g38 commented
> Thanks @suzy-g38 for making the biggest contribution to the Vibey. You have done a really great job and implemented it perfectly. Let's merge the pr!

Thanks a lot, @Deepu178, I think as a contributor these words mean a lot, and there is no greater satisfaction than this. Thank you.