solved issue of Navbar responsiveness
UniKonf/Vibey pull request #88
Opened 2023-04-23 07:42 UTC by Mudassirkhan2

solved the issue of navbar responsiveness by removing github logo for small devices and decreasing padding-x for button get started  
![Screenshot 2023-04-23 130933](https://user-images.githubusercontent.com/106579572/233826621-9389bbc2-a4dd-4dcb-83f5-392df0322e1e.png)

2023-04-24 13:41 UTC, Deepu178 requested changes
Actuall, you installed dependencies using npm but we have recently shifted to yarn package manager. add the dependencies using yarn.

2023-04-25 00:26 UTC, Chandraprakash-Darji requested changes

2023-04-25 00:26 UTC, Chandraprakash-Darji commented on yarn.lock
> -  resolved "https://registry.yarnpkg.com/@algolia/cache-browser-local-storage/-/cache-browser-local-storage-4.17.0.tgz#4c54a9b1795dcc1cd9f9533144f7df3057984d39"
undo this file changes

2023-04-25 00:26 UTC, Chandraprakash-Darji commented on src/components/Buttons/Button.tsx
> -          'inline-flex items-center rounded-full',
don't change button style, instead where button is used, just pass there classname,

2023-04-25 06:45 UTC, Mudassirkhan2 commented
#88

2023-04-25 06:45 UTC, closed without merging